segtree cuy
jonathanirvings/training-gate-id pull request #2
Opened 2021-04-10 14:14 UTC by afaji

2021-04-11 23:43 UTC, gyosh requested changes

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +  \item Segment Tree merupakan struktur data alternatif untuk menyelesaikan persoalan Range Sum Query.
di buku perlu dijelasin kalo segment tree itu lebih umum dari BIT. Jadi sebenarnya BIT yang jadi alternatif, ya gak sih?

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +  \item Misalkan kita memiliki array berukuran N. Segment Tree dari array tersebut memiliki log N tingkat, masing-masing tingkat merepresentasikan segmen berukuran $2^l$.
bikin jadi O(log N) tingkat

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +  \item Misalkan kita memiliki array berukuran N. Segment Tree dari array tersebut memiliki log N tingkat, masing-masing tingkat merepresentasikan segmen berukuran $2^l$.
trus kalo perlu pake huruf L di rumus, pakenya `\ell` biar gak bingung itu l, I, atau 1

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +  build(idx * 2 + 1, l, mid); // rekursif ke kiri
kalo segtree lu one based, indeks anaknya 2n dan 2n+1

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +bulid(1, 0, N); // pemanggilan awal
build(1, 1, N)

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +int st[MAXA];         // informasi segment sum
perlu dijelasin ukuran array ini berapa
harusnya 2\*NEAREST_LARGER_POW2
atau kalo males pakenya 4*N
penjelasan lengkap di bagian implementasi https://kupaskode.blogspot.com/2019/01/petunjuk-coding-segment-tree.html

2021-04-11 23:43 UTC, gyosh commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +\frametitle{Lazy Propagation}
ini di luar silabus kan?

2021-07-20 00:36 UTC, afaji commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +\frametitle{Lazy Propagation}
iya goz, tapi ini ditaro aja soalnya buat PKL.

2021-07-20 01:42 UTC, afaji commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +bulid(1, 0, N); // pemanggilan awal
kan ini range-nya goz? 
dari 0 .. N?

2021-07-20 01:46 UTC, afaji commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +  \item Segment Tree merupakan struktur data alternatif untuk menyelesaikan persoalan Range Sum Query.
iya sih, kalo slide ini BIT yang duluan soalnya.

2021-07-20 05:57 UTC, jonathanirvings commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +bulid(1, 0, N); // pemanggilan awal
Lu indexing elementnya one-based (1..N) juga kan, jadi bener kata Goz, `build(1, 1, N)`. Udah gw benerin

2021-07-20 06:01 UTC, jonathanirvings commented on topik/pemrograman-kompetitif-lanjutan/03-struktur-data-lanjutan/pemrograman-kompetitif-lanjutan_03-struktur-data-lanjutan.tex
> +  \includegraphics[width=10cm]{asset/segtree-update-lazy.png}
Gambar ini update lazynya gak sesuai dengan terminologi/kode lazy di slide. Kalau ngikutin kode di slide, harusnya "Lazy +2" nya di node yang berwarna merah.

@afaji Lu bisa update gambarnya ga? Kalau gabisa, mungkin satu slide ilustrasi ini bisa dihapus aja (agak misleading)

2021-07-20 10:03 UTC, merged